esphome:
  name: luku-ir
  includes:
    - sensorMeterHeating.h
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: " Hotspot"
    password: ""

captive_portal:
    
sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new SensorMeterHeating();
    App.register_component(my_sensor);
    return {my_sensor->sensor_kWh, my_sensor->sensor_m3};

  sensors:
  - name: "Meter Heating MWh"
    unit_of_measurement: MWh
    accuracy_decimals: 3
  - name: "Meter Heating m3"
    unit_of_measurement: m3
    accuracy_decimals: 2
